######################################################################
# Automatically generated by qmake (3.0) Wed Jul 2 23:19:23 2014
######################################################################

TEMPLATE = lib
TARGET = t03
INCLUDEPATH += .

# Input
SOURCES += test.cpp
QT += widgets
