######################################################################
# Automatically generated by qmake (3.0) Tue Jun 10 14:03:19 2014
######################################################################

TEMPLATE = app
TARGET = t01
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += t01.cpp
