######################################################################
# Automatically generated by qmake (3.0) Tue Jun 10 14:04:20 2014
######################################################################

TEMPLATE = app
TARGET = t02
INCLUDEPATH += .
QT += widgets

# Input
SOURCES += t02.cpp
